name: abdc-gcloud

on:
  push:
    branches: [main]

env:
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  CLOUD_RUN_PROJECT_ID: abdc-gmb
  CLOUD_RUN_REGION: europe-west1
  IMAGE_NAME: gcr-test
  SERVICE_NAME: gcr-test

  # project env
  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
  NEXT_PUBLIC_STRIPE_APIKEY: ${{ secrets.NEXT_PUBLIC_STRIPE_APIKEY }}

jobs:
  build-and-deploy-dev:
    name: Build and Push to DEV
    environment: DEV
    runs-on: ubuntu-latest
    env:
      NAME: ${{ secrets.NAME }}
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Enable the necessary APIs and enable docker auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Build and tag image
        run: |-
          echo NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL >> .env
          echo NEXT_PUBLIC_STRIPE_APIKEY=$NEXT_PUBLIC_STRIPE_APIKEY >> .env
          docker build -t $IMAGE_NAME:latest .

      - name: Push Docker Image to Artifact Registry
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$CLOUD_RUN_PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$CLOUD_RUN_PROJECT_ID/$IMAGE_NAME:v0.0.1
          docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$IMAGE_NAME:v0.0.1

      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.CLOUD_RUN_PROJECT_ID }}/${{ env.IMAGE_NAME }}:v0.0.1
          region: ${{ env.CLOUD_RUN_REGION }}
          flags: "--allow-unauthenticated"
